/*
 * Local copy of Wine WinUSB IOCTL codes for wineusb.sys
 */

#ifndef __WINE_WINUSBIOCTL_H
#define __WINE_WINUSBIOCTL_H

#include <winioctl.h>

#define IOCTL_WINEUSB_GET_CONFIG_DESCRIPTOR \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINEUSB_CONTROL_TRANSFER \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINEUSB_READ_PIPE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINEUSB_WRITE_PIPE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINEUSB_ABORT_PIPE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINEUSB_SET_INTERFACE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_WINEUSB_QUERY_DEVICE_INFO \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)

/* IOCTL_WINEUSB_SET_INTERFACE: Input = UCHAR interface_number, UCHAR alternate_setting. */
/* IOCTL_WINEUSB_QUERY_DEVICE_INFO: Input = ULONG InformationType (DEVICE_SPEED=1). Output = value (e.g. ULONG speed). */

#endif /* __WINE_WINUSBIOCTL_H */


